# Generated by Django 3.0.7 on 2020-06-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200622_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='comments',
            field=models.TextField(default='This is a great update!'),
            preserve_default=False,
        ),
    ]
