# Generated by Django 3.0.7 on 2020-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='comments',
            field=models.TextField(default='This is a good update!'),
            preserve_default=False,
        ),
    ]
