# Generated by Django 3.0.7 on 2020-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='contact_bc_cole',
            field=models.DateTimeField(verbose_name='Contact B/C Cole - Date and Time'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='hospital_number',
            field=models.CharField(max_length=5, verbose_name='Hospital #'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='incident_number',
            field=models.CharField(max_length=9, verbose_name='Incident #'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='provider_name',
            field=models.CharField(max_length=30, verbose_name='Provider Name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='rsi_kit_seal_number',
            field=models.CharField(max_length=5, verbose_name='RSI Kit #1 Seal #'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='shift_hours',
            field=models.DurationField(verbose_name='Shift Hours'),
        ),
    ]
