# Generated by Django 3.0.7 on 2020-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_auto_20200623_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='contact_bc_cole',
            field=models.DateTimeField(help_text='Please display in the form yyyy-mm-dd hh:mm:ss!', verbose_name='Contact B/C Cole - Date and Time'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='date',
            field=models.DateField(help_text='Please display in the form hh:mm:ss!'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='shift_hours',
            field=models.DurationField(help_text='Please display in the form yyyy-mm-dd!', verbose_name='Shift Hours'),
        ),
    ]
