# Generated by Django 3.0.7 on 2020-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narcotics', '0003_auto_20200622_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='narcotic',
            name='comments',
            field=models.TextField(default='Good update!'),
            preserve_default=False,
        ),
    ]
