# Generated by Django 3.0.7 on 2020-06-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narcotics', '0004_narcotic_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narcotic',
            name='incident_number',
            field=models.CharField(blank=True, max_length=9, verbose_name='Incident #'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='medication_amount_mg',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Medication Amount (in mg)'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='medication_used',
            field=models.CharField(blank=True, max_length=10, verbose_name='Medication Used'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='waste_witness_initials',
            field=models.CharField(blank=True, max_length=2, verbose_name='Waste Witness Initials'),
        ),
    ]
